export const TENANT_TEXT_KEYS = {
  SUPPORT_HOURS: 'serviceTime',
  SUPPORT_PHONE_NUMBER: 'phoneNumber',
  SUPPORT_PHONE_NUMBER_FORMATTED: 'phoneNumberFormatted',
  SUPPORT_EMAIL: 'supportEmail',
  SUPPORT_HOURS_DATE: 'serviceTimeDate',
  PAGE_TITLE: 'pageTitle',
  PRIVACY_POLICY: 'privacyPolicy',
} as const;

export const TENANT_SUBORGANIZATION_CODES = {
  AMA: 'AMA',
  ATL: 'ATL',
  BCAA: 'BCAA',
  MAN: 'MAN',
  NEO: 'NEO',
  NIA: 'NIA',
  QUE: 'QUE',
  SCON: 'SCON',
  SASK: 'SASK',
} as const;

export const CAA_MEMBER_DOMAIN = {
  EN: 'life-health',
  FR: 'vie-sante',
} as const;

export const PUBLIC_KEYS = {
  AUTH0_CLIENT_ID: 'AUTH0_CLIENT_ID',
  AUTH0_HOST: 'AUTH0_HOST',
  STRIPE: 'STRIPE',
  SEGMENT: 'SEGMENT',
  // TODO: Remove these PM-specific keys analytics once segment is set up
  FACEBOOK: 'FACEBOOK',
} as const;

export const TENANT_OVERRIDE_SLOTS = {
  COMPLAINTS_LINK_SLOT: 'complaints-link-slot',
  SUPPORT_EMAIL_SLOT: 'support-email-slot',
  QUOTES_CONTINUED_CTA: 'quotes-continued-cta',
  MONEY_BACK_GUARANTEE: 'money-back-guarantee',
} as const;

export const GROUP_NAMES = [
  'IBEW Local 625',
  'IBEW Local 1852',
  'U.A. Local 682',
  'Labourers Atlantic Region District Council',
  'Health and Wellness Trust (4 Locals)',
  'IBEW Local 1555',
  'Heat & Frost Insulators & Allied Workers Local 116',
  'International Longshoremen\'s Association / Halifax Port',
  'IBEW Local 502',
  'Atlantic Canada Regional Council of Carpenters, Millwrights & Allied Workers (5 Locals)',
  'IBEW Local 2166',
  'Unifor Atlantic Communications Council',
  'Sheet Metal Workers & Roofers Local 56',
  'IBEW Local 1928',
  'Sheet Metal Workers Local 409',
  'IBEW Local 37',
  'IBEW Local 1928/N.S. Power',
  'Heat & Frost Insulators & Allied Workers Local 137',
  'Federal Government Dockyard Trades & Labour Council (10 Unions)',
  'IBEW Local 1620',
  'Nova Scotia Government Retired Employees Association',
  'Nova Scotia Government & General Employees Union',
  'Ironworkers Local 752',
  'IBEW Local 1928/UPEI',
  'Intl. Union of Painters & Allied Trades District Council #39',
  'Steel Workers Local 5319 Benefit Plan',
  'UFCW Local 361, B&SDW',
  'United Steelworkers (85 Locals)',
  'BCTGM Local 446',
  'UNIFOR Local 434',
  'Heat & Frost Insulators & Allied Workers Local 131',
  'Sheet Metal Workers Local 437',
  'Operating Engineers Local 946',
  'Atlantic Police Association Benefit Plan',
  'CUPE NS',
  'UA Local 56',
  'Bricklayers & Allied Craftworkers International Health Fund',
  'IATSE Local 849',
  'Strescon Bedford Health Plan',
  'Lunenburg Foundry & Engineering Ltd Benefit Plan',
  'ILA Local 273 / PSJEA Benefit Plan',
  'International Association of Machinists & Aerospace Workers Local 1763',
  'South Shore Community Service Association / UNIFOR Local 2001 Benefit Plan',
  'UNIFOR Local 40 Agropar Cooperative Ltd Benefits Plan',
  'UNIFOR Atlantic Communications Local',
  'Amalgamated Transit Union Local 508',
  'UNIFOR Local 2215',
  'UFCW Canada Eastern Provinces Council',
  'Public Service Alliance of Canada',
  'Eddy Group Benefit Plan',
  'Teamsters Local 927',
  'BCTGM Local 406',
  'CUPE',
  'IBEW Local 1318',
  'Atlantic Federation of Musicians Local 571',
  'UNIFOR Local 4005',
  'Canadian Union of Postal Workers',
  'SEIU Local 2 Branch',
  'CUPE NL',
  'PEI UPSE',
  'Federal Government Dockyard Chargehands Association',
  'UA Local 740',
  'Dartmouth Fire Veterans Association',
  'IBEW Local 1615',
  'UNIFOR MWF Local 1',
  'NS Union of Public & Private Employees',
  'Iron Workers Local 764 Pension & Benefits Trust Fund',
  'IATSE Local 709',
  'Halifax Typographical Union',
  'UNIFOR Local 2121',
  'UA Local 721',
  'NB UA PIPE Trades',
  'NB Union of Public & Private Employees',
  'IBEW Local 2330',
  'UNIFOR Council of Irving Locals',
  'Iron Workers Local 842',
  'UNIFOR Local 20 MWF',
  'UNIFOR Local 972',
  'UNIFOR Local 4606',
  'IBEW Local 1651',
  'IUOE Local 942',
  'Amalgamated Transit Union Local 1462',
  'IUOE Local 727',
  'NAPE',
  'ILA Local 1953',
  'Amalgamated Transit Union Local 1290',
  'IBEW Local 1524',
  'Amalgamated Transit Union Local 1182',
  'St John\'s Firefighters Local 1075',
  'Association of Allied Health Professionals',
] as const;
