export interface FormData {
    address_line1: string
    address_line2: string
    alcohol_flag: string
    alcohol_num_drinks: string
    alcohol_drug_abuse: string
    alcohol_frequency: string
    alcohol_type_beer: string
    alcohol_type_liquor: string
    alcohol_type_wine: string
    arrested: string
    arrested_details: string
    bankruptcy: string
    bankruptcy_details: string
    beneficiaries: {}
    beneficiaries_secondary_flag: string
    birthplace: string
    birthplace_provstate: string
    borrowed: string
    borrowed_details: string
    business_type: string
    canadian_taxes: string
    city: string
    country: string
    drivers_license_flag: string
    driving_conviction_alcohol_ML: string
    driving_conviction_alcohol_details_ML: string
    driving_conviction_dangerous_ML: string
    driving_conviction_dangerous_details_ML: string
    driving_conviction_violation_ML: string
    driving_conviction_violation_details_ML: string
    driving_conviction_violation_BMO: string
    driving_conviction_violation_details_BMO: string
    driving_conviction_dangerous_5_BMO: string
    driving_conviction_dangerous_5_details_BMO: string
    driving_conviction_dangerous_10_BMO: string
    driving_conviction_dangerous_10_details_BMO: string
    driving_conviction_violation_WW: string
    driving_conviction_violation_details_WW: string
    driving_conviction_dangerous_5_WW: string
    driving_conviction_dangerous_5_details_WW: string
    driving_conviction_dui_WW: string
    driving_conviction_dui_details_WW: string
    employed: string
    employer: string
    employer_city: string
    employment_status: string
    employment_status_other: string
    ever_declined_rated: string
    ever_declined_rated_details: string
    existing_policies_inforce_flag: string
    existing_policies_replacing_flag: string
    existing_policies_pending_flag: string
    existing_policies_pending_keeping_flag: string
    existing_policies: {}
    experiment_drugs: string
    experiment_drugs_details: string
    extreme_flag: string
    extreme: any[]
    financial_difficulties: string
    financial_difficulties_details: string
    health_provider_flag: string
    health_provider_phone_number: string
    healthcare_provider: string
    healthcare_provider_city: string
    healthcare_provider_month: string
    healthcare_provider_year: string
    healthcare_visit_flag: string
    healthcare_visit_has_meds: string
    healthcare_visit_meds: string
    healthcare_visit_reason: string
    healthcare_visit_reason_details: string
    healthcare_visit_result: string
    healthcare_visit_result_details: string
    height_feet: string
    height_inches: string
    identification_type: string
    identification_expiry_date: string
    identification_number: string
    identification_place_of_issue: string
    is_pilot: string
    is_pilot_WW: string
    license: string
    license_suspended: string
    license_suspended_details: string
    mortgage_balance_override: string
    occupation: string
    occupation_change: string
    other_debts_override: string
    other_income_amount: string
    other_income_flag: string
    other_income_source: string
    perm_res_date: string
    postal_code: string
    previous_country_residence: string
    primary_residence: string
    province: string
    questions: string
    residency_status: string
    residency_applied_perm_res: string
    residency_canada_12months: string
    residency_domestic_worker: string
    residency_foreign_trained_physician: string
    residency_skilled_worker: string
    tobacco_flag: string
    tobacco_chewing: string
    tobacco_chewing_current: string
    tobacco_chewing_frequency: string
    tobacco_chewing_quit: string
    tobacco_cigarettes: string
    tobacco_cigarettes_current: string
    tobacco_cigarettes_frequency: string
    tobacco_cigarettes_quit: string
    tobacco_cigars_cigarillos: string
    tobacco_cigars_cigarillos_current: string
    tobacco_cigars_cigarillos_frequency: string
    tobacco_cigars_cigarillos_quit: string
    tobacco_e_cigarettes: string
    tobacco_e_cigarettes_current: string
    tobacco_e_cigarettes_frequency: string
    tobacco_e_cigarettes_quit: string
    tobacco_marijuana: string
    tobacco_marijuana_current: string
    tobacco_marijuana_frequency: string
    tobacco_marijuana_quit: string
    tobacco_marijuana_use: string
    tobacco_pipes: string
    tobacco_pipes_current: string
    tobacco_pipes_frequency: string
    tobacco_pipes_quit: string
    tobacco_substitutes: string
    tobacco_substitutes_current: string
    tobacco_substitutes_frequency: string
    tobacco_substitutes_quit: string
    travel_past_trips_flag: string
    travel_trips: TravelTrips
    travel_future_trips_flag: string
    travel_future_non_urban_flag: string
    travel_future_non_urban_details: string
    travel_future_war_zone_flag: string
    travel_future_war_zone_details: string
    trustee_first_name: string
    trustee_flag: string
    trustee_last_name: string
    trustee_relationship: string
    weight_change: string
    weight_change_details: string
    weight_lbs: string
    years_at_address: string
    years_at_employer: string
  }

interface TravelTrips {}
