import store from '../../src/store';
import { getStore } from '../utils';

const storeName = 'lifeApp';
const data = getStore(`primary/${storeName}`);
const initialState = data || {
  schemaVersion: '2.4.0',
  formMetaData: {
    // Needed to order the rows correctly cross-browser on the UI since JavaScript objects don't
    // guarantee order
    beneficiary_keys: [
      'le-N-1pP-',
      'oeysjz8CWW',
      'Id6YjXSmrB',
    ],
  },
  formData: {
    address_line1: '12 Bonnycastle Street',
    address_line2: '',
    alcohol_drug_abuse: '',
    alcohol_flag: '',
    alcohol_frequency: '',
    alcohol_num_drinks: '',
    alcohol_type_beer: '',
    alcohol_type_liquor: '',
    alcohol_type_wine: '',
    arrested: '',
    arrested_details: '',
    bankruptcy: '',
    bankruptcy_details: '',
    beneficiaries: {
      Id6YjXSmrB: {
        dob: '',
        name: '',
        percent: 50,
        relationship: 'Child',
        type: 'secondary',
      },
      'le-N-1pP-': {
        dob: '',
        name: 'Test Spouse',
        percent: 100,
        relationship: 'Spouse',
        type: 'primary',
      },
      oeysjz8CWW: {
        dob: '',
        name: '',
        percent: 50,
        relationship: 'Child',
        type: 'secondary',
      },
    },
    beneficiaries_secondary_flag: 'N',
    birthplace: 'CA',
    birthplace_provstate: 'AB',
    borrowed: 'N',
    borrowed_details: '',
    business_type: '',
    canadian_taxes: '',
    city: 'Toronto',
    country: 'CA',
    drivers_license_flag: '',
    driving_conviction_alcohol_ML: '',
    driving_conviction_alcohol_details_ML: '',
    driving_conviction_dangerous_5_BMO: '',
    driving_conviction_dangerous_5_WW: '',
    driving_conviction_dangerous_5_details_BMO: '',
    driving_conviction_dangerous_5_details_WW: '',
    driving_conviction_dangerous_10_BMO: '',
    driving_conviction_dangerous_10_details_BMO: '',
    driving_conviction_dangerous_ML: '',
    driving_conviction_dangerous_details_ML: '',
    driving_conviction_dui_WW: '',
    driving_conviction_dui_details_WW: '',
    driving_conviction_violation_BMO: '',
    driving_conviction_violation_ML: '',
    driving_conviction_violation_WW: '',
    driving_conviction_violation_details_BMO: '',
    driving_conviction_violation_details_ML: '',
    driving_conviction_violation_details_WW: '',
    employed: 'N',
    employer: '',
    employer_city: '',
    employment_status: '',
    employment_status_other: '',
    ever_declined_rated: '',
    ever_declined_rated_details: '',
    existing_policies: {},
    existing_policies_replacing_flag: '',
    experiment_drugs: '',
    experiment_drugs_details: '',
    extreme: [],
    extreme_flag: '',
    financial_difficulties: 'N',
    financial_difficulties_details: '',
    healthcare_provider: '',
    healthcare_provider_city: '',
    healthcare_provider_month: '',
    healthcare_provider_year: '',
    healthcare_visit_flag: '',
    healthcare_visit_has_meds: '',
    healthcare_visit_meds: '',
    healthcare_visit_reason: '',
    healthcare_visit_reason_details: '',
    healthcare_visit_result: '',
    healthcare_visit_result_details: '',
    height_feet: '',
    height_inches: '',
    identification_expiry_date: '',
    identification_number: '',
    identification_place_of_issue: '',
    identification_type: '',
    is_pilot: '',
    is_pilot_WW: '',
    license: 'N',
    license_suspended: '',
    license_suspended_details: '',
    mortgage_balance_override: '',
    occupation: '',
    occupation_change: '',
    other_debts_override: 0,
    other_income_amount: '',
    other_income_flag: 'N',
    other_income_source: '',
    perm_res_date: '',
    postal_code: 'M5A 3Y4',
    previous_country_residence: '',
    primary_residence: '',
    province: 'ON',
    healthcard_province: 'ON',
    questions: '',
    residency_status: 'citizen',
    residency_applied_perm_res: '',
    residency_canada_12months: '',
    residency_domestic_worker: '',
    residency_foreign_trained_physician: '',
    residency_skilled_worker: '',
    tobacco_chewing: '',
    tobacco_chewing_current: '',
    tobacco_chewing_frequency: '',
    tobacco_chewing_quit: '',
    tobacco_cigarettes: '',
    tobacco_cigarettes_current: '',
    tobacco_cigarettes_frequency: '',
    tobacco_cigarettes_quit: '',
    tobacco_cigars_cigarillos: '',
    tobacco_cigars_cigarillos_current: '',
    tobacco_cigars_cigarillos_frequency: '',
    tobacco_cigars_cigarillos_quit: '',
    tobacco_e_cigarettes: '',
    tobacco_e_cigarettes_current: '',
    tobacco_e_cigarettes_frequency: '',
    tobacco_e_cigarettes_quit: '',
    tobacco_flag: 'N',
    tobacco_marijuana: '',
    tobacco_marijuana_current: '',
    tobacco_marijuana_frequency: '',
    tobacco_marijuana_quit: '',
    tobacco_marijuana_use: '',
    tobacco_pipes: '',
    tobacco_pipes_current: '',
    tobacco_pipes_frequency: '',
    tobacco_pipes_quit: '',
    tobacco_substitutes: '',
    tobacco_substitutes_current: '',
    tobacco_substitutes_frequency: '',
    tobacco_substitutes_quit: '',
    travel_future_trips_flag: '',
    travel_future_non_urban_flag: '',
    travel_future_non_urban_details: '',
    travel_future_war_zone_flag: '',
    travel_future_war_zone_details: '',
    travel_past_trips_flag: '',
    travel_trips: {},
    trustee_first_name: '',
    trustee_flag: '',
    trustee_last_name: '',
    trustee_relationship: '',
    weight_change: '',
    weight_change_details: '',
    weight_lbs: '',
    years_at_address: '3',
    years_at_employer: '',
  },
};

const dataSecondary = getStore(`secondary/${storeName}`);
const secondaryInitialState = dataSecondary || {
  schemaVersion: '2.4.0',
  formMetaData: {
    // Needed to order the rows correctly cross-browser on the UI since JavaScript objects don't
    // guarantee order
    beneficiary_keys: [
      'le-N-1pP-',
      'oeysjz8CWW',
      'Id6YjXSmrB',
    ],
  },
  formData: {
    address_line1: '12 Bonnycastle Street',
    address_line2: '',
    alcohol_drug_abuse: '',
    alcohol_flag: '',
    alcohol_frequency: '',
    alcohol_num_drinks: '',
    alcohol_type_beer: '',
    alcohol_type_liquor: '',
    alcohol_type_wine: '',
    arrested: '',
    arrested_details: '',
    bankruptcy: '',
    bankruptcy_details: '',
    beneficiaries: {
      Id6YjXSmrB: {
        dob: '',
        name: '',
        percent: 50,
        relationship: 'Child',
        type: 'secondary',
      },
      'le-N-1pP-': {
        dob: '',
        name: 'Test Spouse',
        percent: 100,
        relationship: 'Spouse',
        type: 'primary',
      },
      oeysjz8CWW: {
        dob: '',
        name: '',
        percent: 50,
        relationship: 'Child',
        type: 'secondary',
      },
    },
    beneficiaries_secondary_flag: 'N',
    birthplace: 'CA',
    birthplace_provstate: 'AB',
    borrowed: 'N',
    borrowed_details: '',
    business_type: '',
    canadian_taxes: '',
    city: 'Toronto',
    country: 'CA',
    drivers_license_flag: '',
    driving_conviction_alcohol_ML: '',
    driving_conviction_alcohol_details_ML: '',
    driving_conviction_dangerous_5_BMO: '',
    driving_conviction_dangerous_5_WW: '',
    driving_conviction_dangerous_5_details_BMO: '',
    driving_conviction_dangerous_5_details_WW: '',
    driving_conviction_dangerous_10_BMO: '',
    driving_conviction_dangerous_10_details_BMO: '',
    driving_conviction_dangerous_ML: '',
    driving_conviction_dangerous_details_ML: '',
    driving_conviction_dui_WW: '',
    driving_conviction_dui_details_WW: '',
    driving_conviction_violation_BMO: '',
    driving_conviction_violation_ML: '',
    driving_conviction_violation_WW: '',
    driving_conviction_violation_details_BMO: '',
    driving_conviction_violation_details_ML: '',
    driving_conviction_violation_details_WW: '',
    employed: 'N',
    employer: '',
    employer_city: '',
    employment_status: '',
    employment_status_other: '',
    ever_declined_rated: '',
    ever_declined_rated_details: '',
    existing_policies: {},
    experiment_drugs: '',
    experiment_drugs_details: '',
    extreme: [],
    extreme_flag: '',
    financial_difficulties: 'N',
    financial_difficulties_details: '',
    healthcare_provider: '',
    healthcare_provider_city: '',
    healthcare_provider_month: '',
    healthcare_provider_year: '',
    healthcare_visit_flag: '',
    healthcare_visit_has_meds: '',
    healthcare_visit_meds: '',
    healthcare_visit_reason: '',
    healthcare_visit_reason_details: '',
    healthcare_visit_result: '',
    healthcare_visit_result_details: '',
    height_feet: '',
    height_inches: '',
    identification_expiry_date: '',
    identification_number: '',
    identification_place_of_issue: '',
    identification_type: '',
    is_pilot: '',
    is_pilot_WW: '',
    license: 'N',
    license_suspended: '',
    license_suspended_details: '',
    mortgage_balance_override: '',
    occupation: '',
    occupation_change: '',
    other_debts_override: 0,
    other_income_amount: '',
    other_income_flag: 'N',
    other_income_source: '',
    perm_res_date: '',
    postal_code: 'M5A 3Y4',
    previous_country_residence: '',
    primary_residence: '',
    province: 'ON',
    healthcard_province: 'ON',
    questions: '',
    residency_status: 'citizen',
    residency_applied_perm_res: '',
    residency_canada_12months: '',
    residency_domestic_worker: '',
    residency_foreign_trained_physician: '',
    residency_skilled_worker: '',
    tobacco_chewing: '',
    tobacco_chewing_current: '',
    tobacco_chewing_frequency: '',
    tobacco_chewing_quit: '',
    tobacco_cigarettes: '',
    tobacco_cigarettes_current: '',
    tobacco_cigarettes_frequency: '',
    tobacco_cigarettes_quit: '',
    tobacco_cigars_cigarillos: '',
    tobacco_cigars_cigarillos_current: '',
    tobacco_cigars_cigarillos_frequency: '',
    tobacco_cigars_cigarillos_quit: '',
    tobacco_e_cigarettes: '',
    tobacco_e_cigarettes_current: '',
    tobacco_e_cigarettes_frequency: '',
    tobacco_e_cigarettes_quit: '',
    tobacco_flag: 'N',
    tobacco_marijuana: '',
    tobacco_marijuana_current: '',
    tobacco_marijuana_frequency: '',
    tobacco_marijuana_quit: '',
    tobacco_marijuana_use: '',
    tobacco_pipes: '',
    tobacco_pipes_current: '',
    tobacco_pipes_frequency: '',
    tobacco_pipes_quit: '',
    tobacco_substitutes: '',
    tobacco_substitutes_current: '',
    tobacco_substitutes_frequency: '',
    tobacco_substitutes_quit: '',
    travel_future_trips_flag: '',
    travel_future_non_urban_flag: '',
    travel_future_non_urban_details: '',
    travel_future_war_zone_flag: '',
    travel_future_war_zone_details: '',
    travel_past_trips_flag: '',
    travel_trips: {},
    trustee_first_name: '',
    trustee_flag: '',
    trustee_last_name: '',
    trustee_relationship: '',
    weight_change: '',
    weight_change_details: '',
    weight_lbs: '',
    years_at_address: '3',
    years_at_employer: '',
  },
};

function reInitState(user, value) {
  return {
    type: `@@${user}/lifeApp/debug`,
    value,
  };
}

store.dispatch(reInitState('primary', initialState));
store.dispatch(reInitState('secondary', secondaryInitialState));
