import store from '../../src/store';
import { getStore } from '../utils';

const data = getStore('primary/quotes');
const initialState = data || {
  life: {
    userQuotes: {
      individual: [
        {
          applied_discounts: [],
          company: 'PM',
          id: 1,
          invalid: false,
          is_discounted: false,
          is_express: true,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 29.27,
          no_medical: false,
          original_mn_prems: 29.27,
          original_yr_prems: 325.2,
          product_enum: 1003,
          term: 20,
          term_savings: -1,
          yr_prems: 325.2,
        },
        {
          company: 'CL',
          id: 2,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 27.95,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 310.5,
        },
        {
          company: 'ML',
          id: 3,
          invalid: false,
          is_express: true,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 31.06,
          no_medical: false,
          product_enum: 8,
          term: 20,
          yr_prems: 346.6,
        },
        {
          company: 'BMO',
          id: 4,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: true,
          low_approval: false,
          mn_prems: 31.95,
          no_medical: false,
          product_enum: 2,
          term: 20,
          yr_prems: 355,
        },
        {
          company: 'SUL',
          id: 5,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 32.85,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 365,
        },
        {
          company: 'DES',
          id: 6,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 30.15,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 335,
        },
        {
          company: 'EMP',
          id: 7,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 30.6,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 340,
        },
        {
          company: 'RBC',
          id: 8,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 32.18,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 357.5,
        },
        {
          company: 'EQL',
          id: 9,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 33.25,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 369.45,
        },
        {
          company: 'CPP',
          id: 10,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 76.95,
          no_medical: true,
          product_enum: 11,
          term: 20,
          yr_prems: 855,
        },
        {
          company: 'WW',
          id: 11,
          invalid: true,
          is_express: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 0,
          no_medical: false,
          product_enum: 0,
          term: 0,
          yr_prems: 0,
        },
      ],
      seq_num: 1,
    },
    recmdQuotes: {},
    maxCovQuotes: {},
    noMedicalQuotes: {},
  },
  ci: {
    userQuotes: {
      individual: [
        {
          company: 'PM',
          id: 1,
          mn_prems: 6.12,
          yr_prems: 68,
        },
      ],
      seq_num: 1,
    },
    recmdQuotes: {},
    maxCovQuotes: {},
    noMedicalQuotes: {},
  },
};

const secondaryData = getStore('secondary/quotes');
const secondaryInitialState = secondaryData || {
  life: {
    userQuotes: {
      individual: [
        {
          applied_discounts: [],
          company: 'PM',
          id: 1,
          invalid: false,
          is_discounted: false,
          is_express: true,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 29.27,
          no_medical: false,
          original_mn_prems: 29.27,
          original_yr_prems: 325.2,
          product_enum: 1003,
          term: 20,
          term_savings: -1,
          yr_prems: 325.2,
        },
        {
          company: 'CL',
          id: 2,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 27.95,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 310.5,
        },
        {
          company: 'ML',
          id: 3,
          invalid: false,
          is_express: true,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 31.06,
          no_medical: false,
          product_enum: 8,
          term: 20,
          yr_prems: 346.6,
        },
        {
          company: 'BMO',
          id: 4,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: true,
          low_approval: false,
          mn_prems: 31.95,
          no_medical: false,
          product_enum: 2,
          term: 20,
          yr_prems: 355,
        },
        {
          company: 'SUL',
          id: 5,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 32.85,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 365,
        },
        {
          company: 'DES',
          id: 6,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 30.15,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 335,
        },
        {
          company: 'EMP',
          id: 7,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 30.6,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 340,
        },
        {
          company: 'RBC',
          id: 8,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 32.18,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 357.5,
        },
        {
          company: 'EQL',
          id: 9,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 33.25,
          no_medical: false,
          product_enum: -1,
          term: 20,
          yr_prems: 369.45,
        },
        {
          company: 'CPP',
          id: 10,
          invalid: false,
          is_express: false,
          is_low_approval: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 76.95,
          no_medical: true,
          product_enum: 11,
          term: 20,
          yr_prems: 855,
        },
        {
          company: 'WW',
          id: 11,
          invalid: true,
          is_express: false,
          is_slow: false,
          low_approval: false,
          mn_prems: 0,
          no_medical: false,
          product_enum: 0,
          term: 0,
          yr_prems: 0,
        },
      ],
      seq_num: 1,
    },
    recmdQuotes: {},
    maxCovQuotes: {},
    noMedicalQuotes: {},
  },
  ci: {
    userQuotes: {
      individual: [
        {
          company: 'PM',
          id: 1,
          mn_prems: 6.12,
          yr_prems: 68,
        },
      ],
      seq_num: 1,
    },
    recmdQuotes: {},
    maxCovQuotes: {},
    noMedicalQuotes: {},
  },
};

function reInitState(user, product, value) {
  return {
    type: `@@${user}/quotes/${product}/debug`,
    value,
  };
}

store.dispatch(reInitState('primary', 'life', initialState.life));
store.dispatch(reInitState('primary', 'ci', initialState.ci));

store.dispatch(reInitState('secondary', 'life', secondaryInitialState.life));
store.dispatch(reInitState('secondary', 'ci', secondaryInitialState.ci));
