import { APP_FORM_FIELDS, IDENTIFICATION_TYPES, COUNTRY_CODES, IDENTIFICATION_TYPES_WITH_EXPIRY_DATE, IDENTIFICATION_TYPES_WITH_PROVINCE, IDENTIFICATION_TYPE_VALUES, RESIDENCY_STATUSES } from '../utils/const';

// For each dependency object, if the value of checkProperty is not in values, then a blank string
// is sent for each includeProperties property to the database.
export const applicationDataDependencies = [
  {
    checkProperty: APP_FORM_FIELDS.FINANCIAL_DIFFICULTIES,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.FINANCIAL_DIFFICULTIES_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.DRIVING_CONVICTION_VIOLATION_ML,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.DRIVING_CONVICTION_VIOLATION_DETAILS_ML],
  },
  {
    checkProperty: APP_FORM_FIELDS.DRIVING_CONVICTION_DANGEROUS_ML,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.DRIVING_CONVICTION_DANGEROUS_DETAILS_ML],
  },
  {
    checkProperty: APP_FORM_FIELDS.DRIVING_CONVICTION_ALCOHOL_ML,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.DRIVING_CONVICTION_ALCOHOL_DETAILS_ML],
  },
  {
    checkProperty: APP_FORM_FIELDS.DRIVING_CONVICTION_VIOLATION_BMO,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.DRIVING_CONVICTION_VIOLATION_DETAILS_BMO],
  },
  {
    checkProperty: APP_FORM_FIELDS.DRIVING_CONVICTION_DANGEROUS_5_BMO,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.DRIVING_CONVICTION_DANGEROUS_5_DETAILS_BMO],
  },
  {
    checkProperty: APP_FORM_FIELDS.DRIVING_CONVICTION_DANGEROUS_10_BMO,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.DRIVING_CONVICTION_DANGEROUS_10_DETAILS_BMO],
  },
  {
    checkProperty: APP_FORM_FIELDS.ARRESTED,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.ARRESTED_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.EVER_DECLINED_RATED,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.EVER_DECLINED_RATED_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.EMPLOYED,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.OCCUPATION,
      APP_FORM_FIELDS.BUSINESS_TYPE,
      APP_FORM_FIELDS.EMPLOYER,
      APP_FORM_FIELDS.EMPLOYER_CITY,
      APP_FORM_FIELDS.YEARS_AT_EMPLOYER,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.WEIGHT_CHANGE,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.WEIGHT_CHANGE_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.OTHER_INCOME_FLAG,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.OTHER_INCOME_AMOUNT,
      APP_FORM_FIELDS.OTHER_INCOME_SOURCE,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.LICENSE,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.LICENSE_SUSPENDED,
      APP_FORM_FIELDS.LICENSE_SUSPENDED_DETAILS,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.LICENSE_SUSPENDED,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.LICENSE_SUSPENDED_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.IDENTIFICATION_TYPE,
    values: Object.values(IDENTIFICATION_TYPE_VALUES),
    includeProperties: [APP_FORM_FIELDS.IDENTIFICATION_NUMBER],
  },
  {
    checkProperty: APP_FORM_FIELDS.IDENTIFICATION_TYPE,
    values: IDENTIFICATION_TYPES_WITH_EXPIRY_DATE,
    includeProperties: [APP_FORM_FIELDS.IDENTIFICATION_EXPIRY_DATE],
  },
  {
    checkProperty: APP_FORM_FIELDS.IDENTIFICATION_TYPE,
    values: IDENTIFICATION_TYPES_WITH_PROVINCE,
    includeProperties: [APP_FORM_FIELDS.IDENTIFICATION_PLACE_OF_ISSUE],
  },
  {
    checkProperty: APP_FORM_FIELDS.ALCOHOL_FLAG,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.ALCOHOL_NUM_DRINKS,
      APP_FORM_FIELDS.ALCOHOL_FREQUENCY,
      APP_FORM_FIELDS.ALCOHOL_TYPE_BEER,
      APP_FORM_FIELDS.ALCOHOL_TYPE_WINE,
      APP_FORM_FIELDS.ALCOHOL_TYPE_LIQUOR,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.EXPERIMENT_DRUGS,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.EXPERIMENT_DRUGS_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.HEALTHCARE_VISIT_RESULT,
    values: ['abnormal'],
    includeProperties: [APP_FORM_FIELDS.HEALTHCARE_VISIT_RESULT_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.HEALTHCARE_VISIT_HAS_MEDS,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.HEALTHCARE_VISIT_MEDS],
  },
  {
    checkProperty: APP_FORM_FIELDS.HEALTHCARE_VISIT_FLAG,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.HEALTHCARE_PROVIDER,
      APP_FORM_FIELDS.HEALTHCARE_PROVIDER_CITY,
      APP_FORM_FIELDS.HEALTHCARE_PROVIDER_MONTH,
      APP_FORM_FIELDS.HEALTHCARE_PROVIDER_YEAR,
      APP_FORM_FIELDS.HEALTHCARE_VISIT_REASON,
      APP_FORM_FIELDS.HEALTHCARE_VISIT_HAS_MEDS,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.BORROWED,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.BORROWED_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.TRUSTEE_FLAG,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.TRUSTEE_FIRST_NAME,
      APP_FORM_FIELDS.TRUSTEE_LAST_NAME,
      APP_FORM_FIELDS.TRUSTEE_RELATIONSHIP,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.BANKRUPTCY,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.BANKRUPTCY_DETAILS],
  },
  {
    checkProperty: APP_FORM_FIELDS.BIRTHPLACE,
    values: [COUNTRY_CODES.US, COUNTRY_CODES.CA],
    includeProperties: [APP_FORM_FIELDS.BIRTHPLACE_PROVSTATE],
  },
  {
    checkProperty: APP_FORM_FIELDS.EXTREME_FLAG,
    values: ['Y'],
    includeProperties: [APP_FORM_FIELDS.EXTREME],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_FLAG,
    values: ['Y'],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_CHEWING,
      APP_FORM_FIELDS.TOBACCO_CHEWING_CURRENT,
      APP_FORM_FIELDS.TOBACCO_CHEWING_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_CHEWING_QUIT,
      APP_FORM_FIELDS.TOBACCO_CIGARETTES,
      APP_FORM_FIELDS.TOBACCO_CIGARETTES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_CIGARETTES_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_CIGARETTES_QUIT,
      APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS,
      APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_CURRENT,
      APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_QUIT,
      APP_FORM_FIELDS.TOBACCO_E_CIGARETTES,
      APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_QUIT,
      APP_FORM_FIELDS.TOBACCO_MARIJUANA,
      APP_FORM_FIELDS.TOBACCO_MARIJUANA_CURRENT,
      APP_FORM_FIELDS.TOBACCO_MARIJUANA_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_MARIJUANA_QUIT,
      APP_FORM_FIELDS.TOBACCO_PIPES,
      APP_FORM_FIELDS.TOBACCO_PIPES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_PIPES_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_PIPES_QUIT,
      APP_FORM_FIELDS.TOBACCO_SUBSTITUTES,
      APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_FREQUENCY,
      APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_QUIT,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_CHEWING_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_CHEWING_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_CHEWING,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_CHEWING_CURRENT,
      APP_FORM_FIELDS.TOBACCO_CHEWING_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_CIGARETTES_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_CIGARETTES_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_CIGARETTES,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_CIGARETTES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_CIGARETTES_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_CURRENT,
      APP_FORM_FIELDS.TOBACCO_CIGARS_CIGARILLOS_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_E_CIGARETTES,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_E_CIGARETTES_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_MARIJUANA_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_MARIJUANA_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_MARIJUANA,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_MARIJUANA_CURRENT,
      APP_FORM_FIELDS.TOBACCO_MARIJUANA_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_PIPES_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_PIPES_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_PIPES,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_PIPES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_PIPES_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_CURRENT,
    values: ['N'],
    includeProperties: [APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_QUIT],
  },
  {
    checkProperty: APP_FORM_FIELDS.TOBACCO_SUBSTITUTES,
    values: [true],
    includeProperties: [
      APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_CURRENT,
      APP_FORM_FIELDS.TOBACCO_SUBSTITUTES_FREQUENCY,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.RESIDENCY_STATUS,
    values: Object.values(RESIDENCY_STATUSES).filter(type => type !== RESIDENCY_STATUSES.CITIZEN),
    includeProperties: [
      APP_FORM_FIELDS.PREVIOUS_COUNTRY_RESIDENCE,
      APP_FORM_FIELDS.PERM_RES_DATE,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.EMPLOYED,
    values: ['N'],
    includeProperties: [
      APP_FORM_FIELDS.EMPLOYMENT_STATUS,
    ],
  },
  {
    checkProperty: APP_FORM_FIELDS.EMPLOYMENT_STATUS,
    values: ['Other'],
    includeProperties: [APP_FORM_FIELDS.EMPLOYMENT_STATUS_OTHER],
  },
  {
    checkProperty: APP_FORM_FIELDS.RESIDENCY_STATUS,
    values: [
      RESIDENCY_STATUSES.ON_VISA,
      RESIDENCY_STATUSES.ON_WORK_VISA,
      RESIDENCY_STATUSES.ON_STUDENT_VISA,
      RESIDENCY_STATUSES.REFUGEE_STATUS,
    ],
    includeProperties: [APP_FORM_FIELDS.RESIDENCY_APPLIED_PERM_RES],
  },
  {
    checkProperty: APP_FORM_FIELDS.RESIDENCY_STATUS,
    values: [
      RESIDENCY_STATUSES.APPLIED_FOR_PERM_STATUS,
      RESIDENCY_STATUSES.ON_VISA,
      RESIDENCY_STATUSES.ON_WORK_VISA,
      RESIDENCY_STATUSES.ON_STUDENT_VISA,
      RESIDENCY_STATUSES.REFUGEE_STATUS,
    ],
    includeProperties: [
      APP_FORM_FIELDS.RESIDENCY_CANADA_12MONTHS,
      APP_FORM_FIELDS.RESIDENCY_DOMESTIC_WORKER,
      APP_FORM_FIELDS.RESIDENCY_FOREIGN_TRAINED_PHYSICIAN,
      APP_FORM_FIELDS.RESIDENCY_SKILLED_WORKER,
    ],
  },
];
