const DISCOUNT_CODES = {
  JOINT_DISCOUNT_V2: 'Joint Discount V2 - 10% Savings for 12 Months',
  AFFILIATE_DISCOUNT: 'Exclusive Perk - 2 months off',
  PM_EMPLOYEE_DISCOUNT: 'Employee Discount - 15% Savings',
  CAA_DISCOUNT: 'CAA Life/CI Member Discount V1 - 10% Savings',
  CAA_HD_DISCOUNT: 'CAA H&D Member Discount V1 - 5% Savings',
  CI_AFFILIATE_DISCOUNT: 'CI Exclusive Perk V1 - 2 months off',
  TL_AFFILIATE_DISCOUNT: 'TL Exclusive Perk V2 - 2 months off',
  CAA_HD_FAMILY_DISCOUNT: 'CAA H&D Family Discount V1 - 5% Savings',
  PM_SEPT2025_PROMO: 'PM Life September 2025 Discount - 10% Savings for 12 Months',
} as const;

const AFFILIATE_DISCOUNT_CODES_CI = [
  'CI Exclusive Perk V1 - 2 months off',
];

const AFFILIATE_DISCOUNT_CODES_LIFE = [
  'Exclusive Perk - 2 months off',
  'TL Exclusive Perk V2 - 2 months off',
];

const DISCOUNT_TYPES = {
  PERCENT_OFF: 1,
  AMOUNT_OFF: 2,
  PERCENT_OFF_IN_X_NUM_OF_MONTHS: 3,
  AMOUNT_OFF_IN_X_NUM_OF_MONTHS: 4,
} as const;

const DISCOUNT_AMOUNT_TEXT = {
  [DISCOUNT_CODES.JOINT_DISCOUNT_V2]: '10%',
  [DISCOUNT_CODES.PM_EMPLOYEE_DISCOUNT]: '15%',
  [DISCOUNT_CODES.CAA_DISCOUNT]: '10%',
  [DISCOUNT_CODES.CAA_HD_DISCOUNT]: '5%',
  [DISCOUNT_CODES.CAA_HD_FAMILY_DISCOUNT]: '5%',
  [DISCOUNT_CODES.PM_SEPT2025_PROMO]: '10%',
} as const;

const DISCOUNTS_VALUE = {
  [DISCOUNT_CODES.JOINT_DISCOUNT_V2]: 10,
  [DISCOUNT_CODES.PM_EMPLOYEE_DISCOUNT]: 15,
  [DISCOUNT_CODES.CAA_DISCOUNT]: 10,
  [DISCOUNT_CODES.CAA_HD_DISCOUNT]: 5,
  [DISCOUNT_CODES.CAA_HD_FAMILY_DISCOUNT]: 5,
  [DISCOUNT_CODES.PM_SEPT2025_PROMO]: 10,
} as const;

const CAA_DISCOUNTS = [
  DISCOUNT_CODES.CAA_DISCOUNT,
  DISCOUNT_CODES.CAA_HD_DISCOUNT,
] as const;

export {
  DISCOUNT_CODES,
  DISCOUNT_TYPES,
  DISCOUNT_AMOUNT_TEXT,
  CAA_DISCOUNTS,
  AFFILIATE_DISCOUNT_CODES_CI,
  AFFILIATE_DISCOUNT_CODES_LIFE,
  DISCOUNTS_VALUE,
};
