export const STATES_ENUM = {
  DEFAULT: 0,
  DEV_INIT: 1,
  JOINT: 2,
  JOURNEY_1_INDIV: 3, // life + ci cross-sell predecision
  JOURNEY_1_JOINT: 4,
  JOURNEY_1_INDIV_APPROVED: 5, // life + ci cross-sell approved
  JOURNEY_1_JOINT_APPROVED: 6,
  JOURNEY_1_POLICYME_PARTNER: 7,
  JOURNEY_1_JOINT_POLICYME_PARTNER: 8,
  JOURNEY_1_INDIV_MORTGAGE: 9,
  JOURNEY_1_JOINT_MORTGAGE: 10,
  JOURNEY_3_INDIV_APPROVED: 11, // ci + life cross-sell
  JOURNEY_JOINT_IS_POLICY_ME_EMPLOYEE: 12, // joint life + pm employee discount
  JOURNEY_INDIVIDUAL_IS_POLICY_ME_EMPLOYEE: 13, // individual life + pm employee discount
  JOURNEY_INDIVIDUAL_HD_GI: 14,
  JOURNEY_JOINT_HD_GI: 15,
  JOURNEY_INDIVIDUAL_QUEBEC_HOUSEHOLD: 16,
  JOURNEY_JOINT_QUEBEC_HOUSEHOLD: 17,
  JOURNEY_JOINT_CAA_MEMBERSHIP: 18,
  JOURNEY_1_INDIV_DECLINED: 19,
  JOURNEY_1_INDIV_RUW: 20,
  DEFAULT_PAYMENT_COMPLETE: 21,
  JOURNEY_HD_QUOTES: 22,
  JOURNEY_1_INDIV_QUEBEC: 23,
};
