import _ from 'lodash';
import shortid from 'shortid';
import { STATES_ENUM } from './const';
import * as constants from '../../src/utils/const';

const states = {
  [STATES_ENUM.DEFAULT]: {
    initialized: false,
    life_seq_num: 0,
    ci_seq_num: 0,
    paymentSliderDown: false,
    redirectedTo: '',
    isLoading: false,
    hasError: false,
    hasCustomError: false,
    currRoute: '/',
    currentUser: 'primary',
    backPressed: false,
    isQuoting: false,
    fromQuoteCompare: false,
    fromStartApp: false,
    fromDocusign: false,
    fromDropJourney: false,
    dateTime: '',
    question: '',
    isContactModalOpen: false,
    name: '',
    isConfirmationOpen: false,
    isBlockerOpen: false,
    debugFlag: false,
    suggestedEmail: null,
    emailIsDeliverable: false,
    hasLocalHistory: false,
    sentEappsMessage: false,
    isChatbotInitialized: false,
    user_lead_source: '',
    user_lead_source_other: '',
    standard_beneficiary_flag: '',
    fbInitFlag: false,
    fbEventQueue: [],
    abTestBand: 'control',
    segmentBlocked: false,
    docusignUrlStatus: 'uninitialized',
    utm_global_id: '853e9ddb-040d-4983-ad09-5697214e0e3a',
    utm_tracking_id: '0027ef4c-0648-4742-8858-891238674267',
    docusignSource: 0,
    experienceLevel: '',
    isJoint: '',
    isPartnerFormComplete: false,
    verifiedEmails: [],
    hasCheckedSecondaryApp: false,
    eappValidateValue: '',
    eappValidateMedium: '',
    eappValidateShortCode: '',
    app_insurer_url: '',
    numValidateAttemptsRemaining: 7,
    hasSubmittedSecondaryApp: false,
    hasSubmittedABTestData: false,
    isSearchLoading: false,
    consentMIBPull: false,
    consentPrivacyPolicy: false,
    decisionLoadingStep: 0,
    isMakingDecisionRequests: false,
    isAppSubmitComplete: false,
    decisionHasBeenMade: false,
    isComingFromConsentPage: false,
    selectedApprovedSteps: false,
    hasEligibilityIssue: false,
    ineligibleUser: null,
    abRequestInFlight: false,
    konami: false,
    is_download_policy_journey: false,
    advisor_id: '',
    advisor_full_name: '',
    secondary_submitted: false,
    isNoMedicalSelected: false,
    syncNurseVisitClickRate: '',
    noMedicalClickRateStatus: '',
    documentReferrer: '',
    isShadowAccountStartApp: false,
    initialWindowLocationHref: 'http://localhost:3000/hd/',
    locationHistory: [
      '/',
    ],
    fromPrimaryUser: false,
    blockPrimaryPages: false,
    smq_quote_num: '',
    smq_mn_prems: '',
    smq_secondary_mn_prems: '',
    association_complete: false,
    isFirstRendering: true,
    primary: {
      disclosuresAnswered: [],
    },
    secondary: {
      disclosuresAnswered: [],
    },
    fromBlog: false,
    productDocusign: '',
    docusignCallbackType: '',
    primaryReviewEsignCompleted: false,
    secondaryReviewEsignCompleted: false,
    showOptionalEsignCard: false,
    utm_source: 'direct',
    utm_extras: {},
    prevRoute: '',
    existingPolicies: {
      existing_policies_inforce_flag: '',
      existing_policies_replacing_flag: '',
      existing_policies_pending_flag: '',
      existing_policies_pending_keeping_flag: '',
    },
    seenTermSelectPopup: {
      permanentInsurancePopup: false,
      termInsurancePopup: false,
    },
    preAppMainProduct: 'life',
  },
  [STATES_ENUM.DEV_INIT]: {
    initialized: false,
    life_seq_num: 13,
    ci_seq_num: 0,
    paymentSliderDown: false,
    redirectedTo: '',
    isLoading: false,
    hasError: false,
    hasCustomError: false,
    currRoute: '/approved/primary/review-esign-policy',
    currentUser: 'primary',
    backPressed: false,
    forwardPressed: true,
    isQuoting: false,
    fromQuoteCompare: false,
    fromStartApp: false,
    fromDocusign: false,
    fromDropJourney: false,
    dateTime: '',
    question: '',
    isContactModalOpen: false,
    name: '',
    isConfirmationOpen: false,
    isBlockerOpen: false,
    debugFlag: false,
    suggestedEmail: null,
    emailIsDeliverable: true,
    hasLocalHistory: true,
    sentEappsMessage: false,
    isChatbotInitialized: false,
    user_lead_source: 'Linkedin',
    user_lead_source_other: '',
    standard_beneficiary_flag: '',
    fbInitFlag: false,
    fbEventQueue: [],
    abTestBand: 'control',
    segmentBlocked: false,
    docusignUrl: 'https://demo.docusign.net/Signing/MTRedeem/v1/4a93b724-3a5f-4095-a714-5c07bf91dcb4?slt=eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2Iiwia2lkIjoiNjgxODVmZjEtNGU1MS00Y2U5LWFmMWMtNjg5ODEyMjAzMzE3In0.AQYAAAABAAMABwAA9AAX_rzaSAgAAJQSnh-92kgYAAEAAAAAAAAAIQC9AgAAeyJUb2tlbklkIjoiYzMyZjkwZDAtOGYyMy00MzZhLWFlNTctN2Q1MDgxZGRkZjAxIiwiRXhwaXJhdGlvbiI6IjIwMjItMTEtMDJUMTg6MTk6MzIrMDA6MDAiLCJJc3N1ZWRBdCI6IjIwMjItMTEtMDJUMTg6MTQ6MzIuMzM4MDgwOSswMDowMCIsIlJlc291cmNlSWQiOiI1OGRlNjlkMS0wNDIwLTRmMTgtYTYyMC0wN2E5NDZjMTI5Y2YiLCJSZXNvdXJjZXMiOiJ7XCJFbnZlbG9wZUlkXCI6XCI1OGRlNjlkMS0wNDIwLTRmMTgtYTYyMC0wN2E5NDZjMTI5Y2ZcIixcIkFjdG9yVXNlcklkXCI6XCI2ODliY2VlOC1kNDUwLTRmNzAtOTI4MC0yOGUyZjYwMjVjMmZcIixcIlJlY2lwaWVudElkXCI6XCIwMWM4YzdiOS1mMmI0LTRjZGYtYTk4Zi05ODhmNGExMzQyOTRcIixcIkZha2VRdWVyeVN0cmluZ1wiOlwidD0wMzUwOGVlOS1kYmYwLTQ0MjAtODhiYi1jZGEyMmM5OTIyOGRcIixcIkludGVncmF0b3JLZXlcIjpcImQxZDY3NTAwLWEyMzktNDEwNS05MDg2LTdjODZkMzZhYzA3OVwifSIsIlRva2VuVHlwZSI6MSwiQXVkaWVuY2UiOiIyNWUwOTM5OC0wMzQ0LTQ5MGMtOGU1My0zYWIyY2E1NjI3YmYiLCJSZWRpcmVjdFVyaSI6Imh0dHBzOi8vZGVtby5kb2N1c2lnbi5uZXQvU2lnbmluZy9TdGFydEluU2Vzc2lvbi5hc3B4IiwiSGFzaEFsZ29yaXRobSI6MCwiSGFzaFJvdW5kcyI6MCwiVG9rZW5TdGF0dXMiOjAsIklzU2luZ2xlVXNlIjpmYWxzZX0_AIC7OMn-vNpI.e0EN6Z-ucar16Ca1wmeBCmvZCyUSjg73VAXIQa5SuOUbK8Ab0edkhd73rlLZDSdi0VVQbvPPxpPQ9Lt9wQpANsxBydk9_m5BHymbBVQBg5eDyAnVHnb34eghLb9Z6n7508XUbcBJwRUS-VQUJnZFyUS2C98Swakf1axgpQKkENryhynzt1DWRK7TGFQkkDwPJEIzjjZvqDvD1kI-q3s5p2mVXGAqvitqzj0aUXRMIAdVz4oS8O22QIEfBwoketI-kzHX0khrLFummw9u3uqjaT2pVm3alcjk13fQtEYQ5mQDJmJpnHJqeHXQZERh26ls-FRqNFKg-kvCb2ctaL0zpg',
    docusignUrlStatus: 'ready',
    utm_global_id: '853e9ddb-040d-4983-ad09-5697214e0e3a',
    utm_tracking_id: '0027ef4c-0648-4742-8858-891238674267',
    docusignSource: 0,
    experienceLevel: 'novice',
    isJoint: '',
    isPartnerFormComplete: false,
    verifiedEmails: [
      'selby.gomes+test_redux@policyme.com',
    ],
    hasCheckedSecondaryApp: false,
    eappValidateValue: '',
    eappValidateMedium: '',
    eappValidateShortCode: '',
    app_insurer_url: '',
    numValidateAttemptsRemaining: 7,
    hasSubmittedSecondaryApp: false,
    hasSubmittedABTestData: true,
    isSearchLoading: false,
    consentMIBPull: true,
    consentPrivacyPolicy: true,
    decisionLoadingStep: 3,
    isMakingDecisionRequests: false,
    isAppSubmitComplete: true,
    decisionHasBeenMade: true,
    isComingFromConsentPage: true,
    selectedApprovedSteps: false,
    hasEligibilityIssue: false,
    ineligibleUser: null,
    abRequestInFlight: false,
    konami: false,
    is_download_policy_journey: false,
    savings: '$-6,727+',
    advisor_id: 1,
    advisor_full_name: 'Erik Heidebrecht',
    secondary_submitted: false,
    isNoMedicalSelected: false,
    syncNurseVisitClickRate: '',
    noMedicalClickRateStatus: '',
    documentReferrer: '',
    initialWindowLocationHref: 'http://localhost:3000/hd/',
    locationHistory: [
      '/',
      '/questions/intro',
      '/questions/partner',
      '/questions/kids',
      '/questions/birthdate',
      '/questions/gender',
      '/questions/smoke',
      '/questions/health',
      '/questions/income',
      '/questions/residence',
      '/questions/existing-coverage',
      '/questions/savings',
      '/questions/debts',
      '/questions/expenses',
      '/questions/email',
      '/recommendation',
      '/life/quotes',
      '/life/start-app',
      '/application/primary/full-address',
      '/application/birth-location',
      '/application/employment-income-annual-self',
      '/application/existing-policies',
      '/application/pending-policies',
      '/application/primary/disclosure-integration/1',
      '/application/primary/disclosure-integration/10',
      '/application/primary/disclosure-integration/11',
      '/application/primary/disclosure-integration/63',
      '/application/primary/disclosure-integration/64',
      '/application/primary/disclosure-integration/99',
      '/application/primary/disclosure-integration/100',
      '/application/primary/disclosure-integration/101',
      '/application/primary/disclosure-integration/119',
      '/application/primary/disclosure-integration/121',
      '/application/primary/disclosure-integration/126',
      '/application/primary/disclosure-integration/127',
      '/application/primary/disclosure-integration/130',
      '/application/primary/disclosure-integration/131',
      '/application/primary/disclosure-integration/133',
      '/application/primary/disclosure-integration/134',
      '/application/primary/disclosure-integration/135',
      '/application/primary/disclosure-integration/137',
      '/application/primary/disclosure-integration/140',
      '/application/primary/disclosure-integration/142',
      '/application/primary/disclosure-integration/229',
      '/application/contact',
      '/application/referrer',
      '/application/consent',
      '/decision-dashboard',
      '/approved/primary/common-beneficiaries',
      '/approved/primary/review-esign-policy',
    ],
    fromPrimaryUser: false,
    blockPrimaryPages: false,
    smq_quote_num: '',
    smq_mn_prems: '',
    smq_secondary_mn_prems: '',
    association_complete: false,
    isFirstRendering: false,
    primary: {
      disclosuresAnswered: [
        1,
        10,
        11,
        63,
        64,
        99,
        100,
        101,
        119,
        121,
        126,
        127,
        130,
        131,
        133,
        134,
        135,
        137,
        140,
        142,
        229,
      ],
    },
    secondary: {
      disclosuresAnswered: [],
    },
    fromBlog: false,
    productDocusign: '',
    docusignCallbackType: '',
    primaryReviewEsignCompleted: false,
    secondaryReviewEsignCompleted: false,
    showOptionalEsignCard: false,
    utm_source: 'direct',
    utm_extras: {},
    prevRoute: '/approved/primary/common-beneficiaries',
    isBeforeUnloadEnabled: false,
    existingPolicies: {
      existing_policies_inforce_flag: 'N',
      existing_policies_replacing_flag: '',
      existing_policies_pending_flag: 'N',
      existing_policies_pending_keeping_flag: '',
    },
    seenTermSelectPopup: {
      permanentInsurancePopup: false,
      termInsurancePopup: false,
    },
    preAppMainProduct: 'life',
  },
  [STATES_ENUM.JOINT]: {
    initialized: false,
    life_seq_num: 6,
    ci_seq_num: 0,
    paymentSliderDown: false,
    redirectedTo: '',
    isLoading: false,
    hasError: false,
    hasCustomError: false,
    currRoute: '/decision-dashboard',
    currentUser: 'primary',
    backPressed: false,
    forwardPressed: true,
    isQuoting: false,
    fromQuoteCompare: false,
    fromStartApp: false,
    fromDocusign: false,
    fromDropJourney: false,
    dateTime: '',
    question: '',
    isContactModalOpen: false,
    name: '',
    isConfirmationOpen: false,
    isBlockerOpen: false,
    debugFlag: false,
    suggestedEmail: null,
    emailIsDeliverable: true,
    hasLocalHistory: true,
    sentEappsMessage: false,
    isChatbotInitialized: false,
    user_lead_source: 'Conference',
    user_lead_source_other: '',
    standard_beneficiary_flag: '',
    fbInitFlag: false,
    fbEventQueue: [],
    abTestBand: 'control',
    segmentBlocked: false,
    docusignUrlStatus: 'uninitialized',
    utm_global_id: '853e9ddb-040d-4983-ad09-5697214e0e3a',
    utm_tracking_id: '0027ef4c-0648-4742-8858-891238674267',
    docusignSource: 0,
    experienceLevel: 'novice',
    isJoint: '',
    isPartnerFormComplete: true,
    verifiedEmails: [
      'selby.gomes+test_redux_2@policyme.com',
      'selby.gomes+partner_123@policyme.com',
    ],
    hasCheckedSecondaryApp: false,
    eappValidateValue: '',
    eappValidateMedium: '',
    eappValidateShortCode: '',
    app_insurer_url: '',
    numValidateAttemptsRemaining: 7,
    hasSubmittedSecondaryApp: false,
    hasSubmittedABTestData: true,
    isSearchLoading: false,
    consentMIBPull: true,
    consentPrivacyPolicy: true,
    decisionLoadingStep: 3,
    isMakingDecisionRequests: false,
    isAppSubmitComplete: true,
    decisionHasBeenMade: true,
    isComingFromConsentPage: true,
    selectedApprovedSteps: false,
    hasEligibilityIssue: false,
    ineligibleUser: null,
    abRequestInFlight: false,
    konami: false,
    is_download_policy_journey: false,
    savings: '$-39,211+',
    advisor_id: 7,
    advisor_full_name: 'Ivana Govedarica',
    secondary_submitted: false,
    isNoMedicalSelected: false,
    syncNurseVisitClickRate: '',
    noMedicalClickRateStatus: '',
    documentReferrer: '',
    initialWindowLocationHref: 'http://localhost:3000/life',
    locationHistory: [
      '/',
      '/questions/intro',
      '/questions/partner',
      '/questions/kids',
      '/questions/kids-education',
      '/questions/birthdate',
      '/questions/gender',
      '/questions/smoke',
      '/questions/health',
      '/questions/income',
      '/questions/residence',
      '/questions/existing-coverage',
      '/questions/savings',
      '/questions/debts',
      '/questions/expenses',
      '/questions/email',
      '/recommendation',
      '/life/quotes',
      '/life/start-app',
      '/application/primary/full-address',
      '/application/birth-location',
      '/application/employment-income-annual-self',
      '/application/existing-policies',
      '/application/pending-policies',
      '/application/primary/disclosure-integration/1',
      '/application/pending-policies',
      '/application/pending-policies',
      '/application/pending-policies',
      '/application/existing-policies',
      '/application/existing-policies',
      '/application/existing-policies',
      '/application/employment-income-annual-self',
      '/application/employment-income-annual-self',
      '/application/employment-income-annual-self',
      '/application/birth-location',
      '/application/birth-location',
      '/application/birth-location',
      '/application/primary/full-address',
      '/application/primary/full-address',
      '/application/primary/full-address',
      '/life/start-app',
      '/life/start-app',
      '/life/start-app',
      '/life/quotes',
      '/life/quotes',
      '/life/start-app',
      '/application/primary/full-address',
      '/application/partner-same-address',
      '/application/birth-location',
      '/application/employment-income-annual-self',
      '/application/existing-policies',
      '/application/pending-policies',
      '/application/primary-transition',
      '/application/primary/disclosure-integration/1',
      '/application/secondary/disclosure-integration/1',
      '/application/primary/disclosure-integration/10',
      '/application/primary/disclosure-integration/11',
      '/application/secondary/disclosure-integration/10',
      '/application/secondary/disclosure-integration/11',
      '/application/primary/disclosure-integration/63',
      '/application/secondary/disclosure-integration/63',
      '/application/primary/disclosure-integration/64',
      '/application/secondary/disclosure-integration/64',
      '/application/primary/disclosure-integration/99',
      '/application/secondary/disclosure-integration/99',
      '/application/primary/disclosure-integration/100',
      '/application/secondary/disclosure-integration/100',
      '/application/primary/disclosure-integration/101',
      '/application/secondary/disclosure-integration/101',
      '/application/primary/disclosure-integration/119',
      '/application/secondary/disclosure-integration/119',
      '/application/primary/disclosure-integration/121',
      '/application/secondary/disclosure-integration/121',
      '/application/primary/disclosure-integration/126',
      '/application/secondary/disclosure-integration/126',
      '/application/primary/disclosure-integration/127',
      '/application/secondary/disclosure-integration/127',
      '/application/primary/disclosure-integration/130',
      '/application/secondary/disclosure-integration/130',
      '/application/primary/disclosure-integration/131',
      '/application/secondary/disclosure-integration/131',
      '/application/primary/disclosure-integration/133',
      '/application/secondary/disclosure-integration/133',
      '/application/primary/disclosure-integration/134',
      '/application/secondary/disclosure-integration/134',
      '/application/primary/disclosure-integration/135',
      '/application/secondary/disclosure-integration/135',
      '/application/primary/disclosure-integration/137',
      '/application/secondary/disclosure-integration/137',
      '/application/primary/disclosure-integration/140',
      '/application/secondary/disclosure-integration/140',
      '/application/primary/disclosure-integration/142',
      '/application/secondary/disclosure-integration/142',
      '/application/primary/disclosure-integration/229',
      '/application/secondary/disclosure-integration/229',
      '/application/contact',
      '/application/partner-info',
      '/application/referrer',
      '/application/consent',
      '/decision-dashboard',
    ],
    fromPrimaryUser: false,
    blockPrimaryPages: false,
    smq_quote_num: '',
    smq_mn_prems: '',
    smq_secondary_mn_prems: '',
    association_complete: true,
    isFirstRendering: false,
    primary: {
      disclosuresAnswered: [
        1,
        10,
        11,
        63,
        64,
        99,
        100,
        101,
        119,
        121,
        126,
        127,
        130,
        131,
        133,
        134,
        135,
        137,
        140,
        142,
        229,
      ],
    },
    secondary: {
      disclosuresAnswered: [
        1,
        10,
        11,
        63,
        64,
        99,
        100,
        101,
        119,
        121,
        126,
        127,
        130,
        131,
        133,
        134,
        135,
        137,
        140,
        142,
        229,
      ],
    },
    fromBlog: false,
    productDocusign: '',
    docusignCallbackType: '',
    primaryReviewEsignCompleted: false,
    secondaryReviewEsignCompleted: false,
    showOptionalEsignCard: false,
    utm_source: 'direct',
    utm_extras: {},
    prevRoute: '/application/consent',
    partnerConsentMIBPull: true,
    partnerConsentPrivacyPolicy: true,
    existingPolicies: {
      existing_policies_inforce_flag: 'N',
      existing_policies_replacing_flag: '',
      existing_policies_pending_flag: 'N',
      existing_policies_pending_keeping_flag: '',
    },
    seenTermSelectPopup: {
      permanentInsurancePopup: false,
      termInsurancePopup: false,
    },
    preAppMainProduct: 'life',
  },
  [STATES_ENUM.JOURNEY_JOINT_HD_GI]: {
    initialized: false,
    life_seq_num: 0,
    ci_seq_num: 0,
    paymentSliderDown: false,
    redirectedTo: '',
    isLoading: false,
    hasError: false,
    hasCustomError: false,
    currRoute: '/',
    currentUser: 'primary',
    backPressed: false,
    isQuoting: false,
    fromQuoteCompare: false,
    fromStartApp: false,
    fromDocusign: false,
    fromDropJourney: false,
    dateTime: '',
    question: '',
    isContactModalOpen: false,
    name: '',
    isConfirmationOpen: false,
    isBlockerOpen: false,
    debugFlag: false,
    suggestedEmail: null,
    emailIsDeliverable: false,
    hasLocalHistory: false,
    sentEappsMessage: false,
    isChatbotInitialized: false,
    user_lead_source: '',
    user_lead_source_other: '',
    standard_beneficiary_flag: '',
    fbInitFlag: false,
    fbEventQueue: [],
    abTestBand: 'control',
    segmentBlocked: false,
    docusignUrlStatus: 'uninitialized',
    utm_global_id: '853e9ddb-040d-4983-ad09-5697214e0e3a',
    utm_tracking_id: '0027ef4c-0648-4742-8858-891238674267',
    docusignSource: 0,
    experienceLevel: '',
    isJoint: '',
    isPartnerFormComplete: false,
    verifiedEmails: [],
    hasCheckedSecondaryApp: false,
    eappValidateValue: '',
    eappValidateMedium: '',
    eappValidateShortCode: '',
    app_insurer_url: '',
    numValidateAttemptsRemaining: 7,
    hasSubmittedSecondaryApp: false,
    hasSubmittedABTestData: false,
    isSearchLoading: false,
    consentMIBPull: false,
    consentPrivacyPolicy: false,
    decisionLoadingStep: 0,
    isMakingDecisionRequests: false,
    isAppSubmitComplete: false,
    decisionHasBeenMade: false,
    isComingFromConsentPage: false,
    selectedApprovedSteps: false,
    hasEligibilityIssue: false,
    ineligibleUser: null,
    abRequestInFlight: false,
    konami: false,
    is_download_policy_journey: false,
    advisor_id: '',
    advisor_full_name: '',
    secondary_submitted: false,
    isNoMedicalSelected: false,
    syncNurseVisitClickRate: '',
    noMedicalClickRateStatus: '',
    documentReferrer: '',
    initialWindowLocationHref: 'http://localhost:3000/hd/',
    locationHistory: [
      '/',
    ],
    fromPrimaryUser: false,
    blockPrimaryPages: false,
    smq_quote_num: '',
    smq_mn_prems: '',
    smq_secondary_mn_prems: '',
    association_complete: false,
    isFirstRendering: true,
    primary: {
      disclosuresAnswered: [],
    },
    secondary: {
      disclosuresAnswered: [],
    },
    fromBlog: false,
    productDocusign: '',
    docusignCallbackType: '',
    primaryReviewEsignCompleted: false,
    secondaryReviewEsignCompleted: false,
    showOptionalEsignCard: false,
    utm_source: 'direct',
    utm_extras: {},
    prevRoute: '',
    existingPolicies: {
      existing_policies_inforce_flag: '',
      existing_policies_replacing_flag: '',
      existing_policies_pending_flag: '',
      existing_policies_pending_keeping_flag: '',
    },
    seenTermSelectPopup: {
      permanentInsurancePopup: false,
      termInsurancePopup: false,
    },
    preAppMainProduct: 'hd',
  },
};

export class Metadata {
  constructor(strategy) {
    const stateObj = states[strategy] ? states[strategy] : states[STATES_ENUM.DEFAULT];
    const initialStateDeepCopy = _.cloneDeep(stateObj);
    Object.assign(this, initialStateDeepCopy);
  }

  addExisitingPolicies({
    status = 'xyz',
    company = constants.INSURERS.CL,
    amount = 234,
    is_replacing = 'N',
    replacing_reasons = ['cheaper', 'other'],
    replacing_reasons_other = '',
    year_issued = 2019,
    type = 'Term Life Insurance',
    type_other = 'Other',
  } = {}, id = shortid.generate()) {
    this.formData.existing_policies[id] = {
      status,
      company,
      amount,
      is_replacing,
      replacing_reasons,
      replacing_reasons_other,
      year_issued,
      type,
      type_other,
    };
    return this;
  }

  removeExisitingPolicies(id) {
    delete this.formData.existing_policies[id];
    return this;
  }

  removeAllExistingPolicies() {
    this.formData.existing_policies = [];
    return this;
  }

  setMetadataProp(prop, val) {
    this[prop] = val;
    return this;
  }
}
