import _ from 'lodash';
import { STATES_ENUM } from './const';

const states = {
  [STATES_ENUM.DEFAULT]: {
    life: {
      userQuotes: {},
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {},
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.DEV_INIT]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 28.03,
            no_medical: false,
            original_mn_prems: 28.03,
            original_yr_prems: 311.44,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/11/2042',
                  end_idx: 20,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 311.44,
                },
              ],
              monthly: [
                {
                  end_date: '02/11/2042',
                  end_idx: 240,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 28.03,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 311.44,
          },
          {
            company: 'ML',
            id: 2,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'BMO',
            id: 3,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CL',
            id: 4,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'DES',
            id: 5,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EMP',
            id: 6,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EQL',
            id: 7,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'RBC',
            id: 8,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'SUL',
            id: 9,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'WW',
            id: 10,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CPP',
            id: 11,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
        ],
        seq_num: 13,
      },
      recmdQuotes: {
        individual: [
          {
            applied_discounts: [
              "Joint Discount V2 - 10% Savings for 12 Months"
            ],
            company: 'PM',
            id: 1,
            invalid: true,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: null,
            no_medical: false,
            original_mn_prems: null,
            original_yr_prems: null,
            product_enum: 1001,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/11/2032',
                  end_idx: 10,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: null,
                },
              ],
              monthly: [
                {
                  end_date: '02/11/2032',
                  end_idx: 120,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: null,
                },
              ],
            },
            term: 10,
            term_savings: -1,
            yr_prems: null,
          },
          {
            company: 'ML',
            id: 2,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'BMO',
            id: 3,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CL',
            id: 4,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'DES',
            id: 5,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EMP',
            id: 6,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EQL',
            id: 7,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'RBC',
            id: 8,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'SUL',
            id: 9,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'WW',
            id: 10,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CPP',
            id: 11,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
        ],
        seq_num: 1,
      },
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            is_discounted: false,
            mn_prems: 18.58,
            original_mn_prems: 18.58,
            original_yr_prems: 206.48,
            quote_breakdown: {
              annual: [
                {
                  end_date: '28/12/2042',
                  end_idx: 20,
                  start_date: '28/12/2022',
                  start_idx: 0,
                  value: 206.48,
                },
              ],
              monthly: [
                {
                  end_date: '28/12/2042',
                  end_idx: 240,
                  start_date: '28/12/2022',
                  start_idx: 0,
                  value: 18.58,
                },
              ],
            },
            yr_prems: 206.48,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOINT]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [
              'Joint Discount V2 - 10% Savings for 12 Months',
            ],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: true,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 65.07,
            no_medical: false,
            original_mn_prems: 65.07,
            original_yr_prems: 723.02,
            product_enum: 1005,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/11/2023',
                  end_idx: 1,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 650.72,
                },
                {
                  end_date: '02/11/2052',
                  end_idx: 30,
                  start_date: '02/11/2023',
                  start_idx: 1,
                  value: 723.02,
                },
              ],
              monthly: [
                {
                  end_date: '02/11/2023',
                  end_idx: 12,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 58.56,
                },
                {
                  end_date: '02/11/2052',
                  end_idx: 360,
                  start_date: '02/11/2023',
                  start_idx: 12,
                  value: 65.07,
                },
              ],
            },
            term: 30,
            term_savings: -1,
            yr_prems: 723.02,
          },
          {
            company: 'ML',
            id: 2,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'BMO',
            id: 3,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CL',
            id: 4,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'DES',
            id: 5,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EMP',
            id: 6,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EQL',
            id: 7,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'RBC',
            id: 8,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'SUL',
            id: 9,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'WW',
            id: 10,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CPP',
            id: 11,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
        ],
        joint: [
          {
            company: 'PM',
            id: 1,
            invalid: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 108.92,
            no_medical: false,
            product_enum: 0,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/11/2023',
                  end_idx: 1,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 1089.2,
                },
                {
                  end_date: '02/11/2052',
                  end_idx: 30,
                  start_date: '02/11/2023',
                  start_idx: 1,
                  value: 1210.22,
                },
              ],
              monthly: [
                {
                  end_date: '02/11/2023',
                  end_idx: 12,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 98.02000000000001,
                },
                {
                  end_date: '02/11/2052',
                  end_idx: 360,
                  start_date: '02/11/2023',
                  start_idx: 12,
                  value: 108.91999999999999,
                },
              ],
            },
            term: 0,
            yr_prems: 1210.22,
          },
          {
            company: 'ML',
            id: 2,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'BMO',
            id: 3,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CL',
            id: 4,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'DES',
            id: 5,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EMP',
            id: 6,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EQL',
            id: 7,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'RBC',
            id: 8,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'SUL',
            id: 9,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'WW',
            id: 10,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CPP',
            id: 11,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
        ],
        seq_num: 6,
      },
      recmdQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 65.07,
            no_medical: false,
            original_mn_prems: 65.07,
            original_yr_prems: 723.02,
            product_enum: 1005,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/11/2052',
                  end_idx: 30,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 723.02,
                },
              ],
              monthly: [
                {
                  end_date: '02/11/2052',
                  end_idx: 360,
                  start_date: '02/11/2022',
                  start_idx: 0,
                  value: 65.07,
                },
              ],
            },
            term: 30,
            term_savings: -1,
            yr_prems: 723.02,
          },
          {
            company: 'ML',
            id: 2,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'BMO',
            id: 3,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CL',
            id: 4,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'DES',
            id: 5,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EMP',
            id: 6,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'EQL',
            id: 7,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'RBC',
            id: 8,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'SUL',
            id: 9,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'WW',
            id: 10,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
          {
            company: 'CPP',
            id: 11,
            invalid: true,
            is_express: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 0,
            no_medical: false,
            product_enum: 0,
            term: 0,
            yr_prems: 0,
          },
        ],
        seq_num: 1,
      },
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {},
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
    },
  },
  [STATES_ENUM.JOURNEY_1_INDIV]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 20.62,
            no_medical: false,
            original_mn_prems: 20.62,
            original_yr_prems: 229.11,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '24/11/2042',
                  end_idx: 20,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 229.11,
                },
              ],
              monthly: [
                {
                  end_date: '24/11/2042',
                  end_idx: 240,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 20.62,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 229.11,
          },
        ],
        seq_num: 8,
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            is_discounted: false,
            mn_prems: 14.12,
            original_mn_prems: 14.12,
            original_yr_prems: 156.91,
            quote_breakdown: {
              annual: [
                {
                  end_date: '24/11/2042',
                  end_idx: 20,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 156.91,
                },
              ],
              monthly: [
                {
                  end_date: '24/11/2042',
                  end_idx: 240,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 14.12,
                },
              ],
            },
            yr_prems: 156.91,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_JOINT]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [
              'Joint Discount V2 - 10% Savings for 12 Months',
            ],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: true,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 24.03,
            no_medical: false,
            original_mn_prems: 24.03,
            original_yr_prems: 266.98,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/12/2023',
                  end_idx: 1,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 240.28,
                },
                {
                  end_date: '02/12/2042',
                  end_idx: 20,
                  start_date: '02/12/2023',
                  start_idx: 1,
                  value: 266.98,
                },
              ],
              monthly: [
                {
                  end_date: '02/12/2023',
                  end_idx: 12,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 21.63,
                },
                {
                  end_date: '02/12/2042',
                  end_idx: 240,
                  start_date: '02/12/2023',
                  start_idx: 12,
                  value: 24.03,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 266.98,
          },
        ],
        joint: [
          {
            company: 'PM',
            id: 1,
            invalid: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 57.57,
            no_medical: false,
            product_enum: 0,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/12/2023',
                  end_idx: 1,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 575.71,
                },
                {
                  end_date: '02/12/2042',
                  end_idx: 20,
                  start_date: '02/12/2023',
                  start_idx: 1,
                  value: 639.6800000000001,
                },
              ],
              monthly: [
                {
                  end_date: '02/12/2023',
                  end_idx: 12,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 51.82,
                },
                {
                  end_date: '02/12/2042',
                  end_idx: 240,
                  start_date: '02/12/2023',
                  start_idx: 12,
                  value: 57.57,
                },
              ],
            },
            term: 0,
            yr_prems: 639.68,
          },
        ],
        seq_num: 3,
      },
      recmdQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 24.03,
            no_medical: false,
            original_mn_prems: 24.03,
            original_yr_prems: 266.98,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/12/2042',
                  end_idx: 20,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 266.98,
                },
              ],
              monthly: [
                {
                  end_date: '02/12/2042',
                  end_idx: 240,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 24.03,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 266.98,
          },
        ],
        seq_num: 1,
      },
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [
        'Joint Discount V2 - 10% Savings for 12 Months',
      ],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            is_discounted: false,
            mn_prems: 11.38,
            original_mn_prems: 11.38,
            original_yr_prems: 126.44,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/12/2042',
                  end_idx: 20,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 126.44,
                },
              ],
              monthly: [
                {
                  end_date: '02/12/2042',
                  end_idx: 240,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 11.38,
                },
              ],
            },
            yr_prems: 126.44,
          },
        ],
        joint: [
          {
            company: 'PM',
            id: 1,
            mn_prems: 22.33,
            quote_breakdown: {
              annual: [
                {
                  end_date: '02/12/2042',
                  end_idx: 20,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 248.07999999999998,
                },
              ],
              monthly: [
                {
                  end_date: '02/12/2042',
                  end_idx: 240,
                  start_date: '02/12/2022',
                  start_idx: 0,
                  value: 22.33,
                },
              ],
            },
            yr_prems: 248.08,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_INDIV_APPROVED]: {
    life: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 20.62,
            yr_prems: 229.11,
            company: 'PM',
            quote_breakdown: {
              annual: [{ end_date: '02/11/2042', end_idx: 20, start_date: '02/11/2022', start_idx: 0, value: 229.11 }],
              monthly: [{ end_date: '02/11/2042', end_idx: 240, start_date: '02/11/2022', start_idx: 0, value: 20.62 }],
            },
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 14.12,
            yr_prems: 156.91,
            company: 'PM',
            quote_breakdown: {
              annual: [{ end_date: '02/11/2042', end_idx: 20, start_date: '02/11/2022', start_idx: 0, value: 156.91 }],
              monthly: [{ end_date: '02/11/2042', end_idx: 240, start_date: '02/11/2022', start_idx: 0, value: 14.12 }],
            },
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_JOINT_APPROVED]: {
    life: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 24.03,
            yr_prems: 266.98,
            company: 'PM',
            quote_breakdown: {
              annual: [{ end_date: '02/11/2042', end_idx: 20, start_date: '02/11/2022', start_idx: 0, value: 266.98 }],
              monthly: [{ end_date: '02/11/2042', end_idx: 240, start_date: '02/11/2022', start_idx: 0, value: 24.03 }],
            },
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [
        'Joint Discount V2 - 10% Savings for 12 Months',
      ],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 11.38,
            yr_prems: 126.44,
            company: 'PM',
            quote_breakdown: {
              annual: [{ end_date: '02/11/2042', end_idx: 20, start_date: '02/11/2022', start_idx: 0, value: 126.44 }],
              monthly: [{ end_date: '02/11/2042', end_idx: 240, start_date: '02/11/2022', start_idx: 0, value: 11.38 }],
            },
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_POLICYME_PARTNER]: {
    "life": {
      "userQuotes": {
        "individual": [
          {
            "applied_discounts": [
              "Exclusive Perk - 2 months off",
              "TL Exclusive Perk V2 - 2 months off"
            ],
            "company": "PM",
            "id": 1,
            "invalid": false,
            "is_discounted": true,
            "is_express": true,
            "is_low_approval": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 36.74,
            "no_medical": false,
            "original_mn_prems": 36.74,
            "original_yr_prems": 408.2,
            "product_enum": 1005,
            "quote_breakdown": {
              "annual": [
                {
                  "end_date": "30/01/2025",
                  "end_idx": 1,
                  "start_date": "30/01/2024",
                  "start_idx": 0,
                  "value": 273.49
                },
                {
                  "end_date": "30/01/2054",
                  "end_idx": 30,
                  "start_date": "30/01/2025",
                  "start_idx": 1,
                  "value": 408.2
                }
              ],
              "monthly": [
                {
                  "end_date": "29/02/2024",
                  "end_idx": 1,
                  "start_date": "30/01/2024",
                  "start_idx": 0,
                  "value": 0.01
                },
                {
                  "end_date": "30/03/2024",
                  "end_idx": 2,
                  "start_date": "29/02/2024",
                  "start_idx": 1,
                  "value": 0
                },
                {
                  "end_date": "30/01/2054",
                  "end_idx": 360,
                  "start_date": "30/03/2024",
                  "start_idx": 2,
                  "value": 36.74
                }
              ]
            },
            "term": 30,
            "term_savings": -1,
            "yr_prems": 408.2
          },
          {
            "company": "ML",
            "id": 2,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "BMO",
            "id": 3,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "CL",
            "id": 4,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "DES",
            "id": 5,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "EMP",
            "id": 6,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "EQL",
            "id": 7,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "RBC",
            "id": 8,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "SUL",
            "id": 9,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "WW",
            "id": 10,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          },
          {
            "company": "CPP",
            "id": 11,
            "invalid": true,
            "is_express": false,
            "is_slow": false,
            "low_approval": false,
            "mn_prems": 0,
            "no_medical": false,
            "product_enum": 0,
            "term": 0,
            "yr_prems": 0
          }
        ],
        "seq_num": 1
      },
      "recmdQuotes": {},
      "maxCovQuotes": {},
      "noMedicalQuotes": {},
      "discountCodes": [
        "Exclusive Perk - 2 months off",
        "TL Exclusive Perk V2 - 2 months off"
      ]
    },
    "ci": {
      "userQuotes": {
        "individual": [
          {
            "applied_discounts": [
              "CI Exclusive Perk V1 - 2 months off"
            ],
            "company": "PM",
            "id": 1,
            "is_discounted": true,
            "mn_prems": 10.04,
            "original_mn_prems": 10.04,
            "original_yr_prems": 111.55,
            "quote_breakdown": {
              "annual": [
                {
                  "end_date": "30/01/2025",
                  "end_idx": 1,
                  "start_date": "30/01/2024",
                  "start_idx": 0,
                  "value": 92.59
                },
                {
                  "end_date": "30/01/2054",
                  "end_idx": 30,
                  "start_date": "30/01/2025",
                  "start_idx": 1,
                  "value": 111.55
                }
              ],
              "monthly": [
                {
                  "end_date": "29/02/2024",
                  "end_idx": 1,
                  "start_date": "30/01/2024",
                  "start_idx": 0,
                  "value": 0.01
                },
                {
                  "end_date": "30/03/2024",
                  "end_idx": 2,
                  "start_date": "29/02/2024",
                  "start_idx": 1,
                  "value": 0
                },
                {
                  "end_date": "30/01/2054",
                  "end_idx": 360,
                  "start_date": "30/03/2024",
                  "start_idx": 2,
                  "value": 10.04
                }
              ]
            },
            "yr_prems": 111.55
          }
        ]
      },
      "recmdQuotes": {},
      "maxCovQuotes": {},
      "noMedicalQuotes": {},
      "discountCodes": [
        "CI Exclusive Perk V1 - 2 months off"
      ]
    },
    "hd": {
      "userQuotes": {},
      "recmdQuotes": {},
      "maxCovQuotes": {},
      "noMedicalQuotes": {},
      "discountCodes": []
    }
  },
  [STATES_ENUM.JOURNEY_1_JOINT_POLICYME_PARTNER]: {
    life: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 31.94,
            yr_prems: 354.9,
            company: 'PM',
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [
        'Exclusive Perk - 2 months off',
        'Joint Discount V2 - 10% Savings for 12 Months',
      ],
    },
    ci: {
      userQuotes: {},
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_3_INDIV_APPROVED]: {
    life: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 49.49,
            yr_prems: 549.91,
            company: 'PM',
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [
        'Exclusive Perk - 2 months off',
      ],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            id: 9999,
            invalid: false,
            product_enum: 0,
            term: 0,
            mn_prems: 32.26,
            yr_prems: 358.49,
            company: 'PM',
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_INDIV_MORTGAGE]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 17.66,
            no_medical: false,
            original_mn_prems: 17.66,
            original_yr_prems: 196.27,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '27/02/2043',
                  end_idx: 20,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 196.27,
                },
              ],
              monthly: [
                {
                  end_date: '27/02/2043',
                  end_idx: 240,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 17.66,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 196.27,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            is_discounted: false,
            mn_prems: 15.27,
            original_mn_prems: 15.27,
            original_yr_prems: 169.67,
            quote_breakdown: {
              annual: [
                {
                  end_date: '27/02/2043',
                  end_idx: 20,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 169.67,
                },
              ],
              monthly: [
                {
                  end_date: '27/02/2043',
                  end_idx: 240,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 15.27,
                },
              ],
            },
            yr_prems: 169.67,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_JOINT_MORTGAGE]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [
              'Joint Discount V2 - 10% Savings for 12 Months',
            ],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: true,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 17.66,
            no_medical: false,
            original_mn_prems: 17.66,
            original_yr_prems: 196.27,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '27/02/2024',
                  end_idx: 1,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 176.64,
                },
                {
                  end_date: '27/02/2043',
                  end_idx: 20,
                  start_date: '27/02/2024',
                  start_idx: 1,
                  value: 196.27,
                },
              ],
              monthly: [
                {
                  end_date: '27/02/2024',
                  end_idx: 12,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 15.9,
                },
                {
                  end_date: '27/02/2043',
                  end_idx: 240,
                  start_date: '27/02/2024',
                  start_idx: 12,
                  value: 17.66,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 196.27,
          },
        ],
        joint: [
          {
            company: 'PM',
            id: 1,
            invalid: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 41.57,
            no_medical: false,
            product_enum: 0,
            quote_breakdown: {
              annual: [
                {
                  end_date: '27/02/2024',
                  end_idx: 1,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 415.7,
                },
                {
                  end_date: '27/02/2043',
                  end_idx: 20,
                  start_date: '27/02/2024',
                  start_idx: 1,
                  value: 461.89,
                },
              ],
              monthly: [
                {
                  end_date: '27/02/2024',
                  end_idx: 12,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 37.42,
                },
                {
                  end_date: '27/02/2043',
                  end_idx: 240,
                  start_date: '27/02/2024',
                  start_idx: 12,
                  value: 41.57,
                },
              ],
            },
            term: 0,
            yr_prems: 461.89,
          },
        ],
        seq_num: 1,
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [
        'Joint Discount V2 - 10% Savings for 12 Months',
      ],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            is_discounted: false,
            mn_prems: 15.27,
            original_mn_prems: 15.27,
            original_yr_prems: 169.67,
            quote_breakdown: {
              annual: [
                {
                  end_date: '27/02/2043',
                  end_idx: 20,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 169.67,
                },
              ],
              monthly: [
                {
                  end_date: '27/02/2043',
                  end_idx: 240,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 15.27,
                },
              ],
            },
            yr_prems: 169.67,
          },
        ],
        joint: [
          {
            company: 'PM',
            id: 1,
            mn_prems: 29.89,
            quote_breakdown: {
              annual: [
                {
                  end_date: '27/02/2043',
                  end_idx: 20,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 332.14,
                },
              ],
              monthly: [
                {
                  end_date: '27/02/2043',
                  end_idx: 240,
                  start_date: '27/02/2023',
                  start_idx: 0,
                  value: 29.89,
                },
              ],
            },
            yr_prems: 332.14,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
  [STATES_ENUM.JOURNEY_1_INDIV_QUEBEC]: {
    life: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            invalid: false,
            is_discounted: false,
            is_express: true,
            is_low_approval: false,
            is_slow: false,
            low_approval: false,
            mn_prems: 20.62,
            no_medical: false,
            original_mn_prems: 20.62,
            original_yr_prems: 229.11,
            product_enum: 1003,
            quote_breakdown: {
              annual: [
                {
                  end_date: '24/11/2042',
                  end_idx: 20,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 229.11,
                },
              ],
              monthly: [
                {
                  end_date: '24/11/2042',
                  end_idx: 240,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 20.62,
                },
              ],
            },
            term: 20,
            term_savings: -1,
            yr_prems: 229.11,
          },
        ],
        seq_num: 8,
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
    ci: {
      userQuotes: {
        individual: [
          {
            applied_discounts: [],
            company: 'PM',
            id: 1,
            is_discounted: false,
            mn_prems: 14.12,
            original_mn_prems: 14.12,
            original_yr_prems: 156.91,
            quote_breakdown: {
              annual: [
                {
                  end_date: '24/11/2042',
                  end_idx: 20,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 156.91,
                },
              ],
              monthly: [
                {
                  end_date: '24/11/2042',
                  end_idx: 240,
                  start_date: '24/11/2022',
                  start_idx: 0,
                  value: 14.12,
                },
              ],
            },
            yr_prems: 156.91,
          },
        ],
      },
      recmdQuotes: {},
      maxCovQuotes: {},
      noMedicalQuotes: {},
      discountCodes: [],
    },
  },
};

export class Quotes {
  constructor(strategy) {
    const stateObj = states[strategy] ? states[strategy] : states[STATES_ENUM.DEFAULT];
    const initialStateDeepCopy = _.cloneDeep(stateObj);
    Object.assign(this, initialStateDeepCopy);
  }

  removePrimaryQuoteByInsurer(insurer) {
    this.userQuotes = this.userQuotes.primary.filter(q => q.company !== insurer);
    return this;
  }

  removeJointQuoteByInsurer(insurer) {
    this.userQuotes = this.userQuotes.primary.filter(q => q.company !== insurer);
    return this;
  }

  setUserPrimaryQuoteProp(id, propName, val) {
    this.life.userQuotes.individual.filter(q => q.id === id)[0][propName] = val;
    return this;
  }

  setUserJointQuoteProp(id, propName, val) {
    this.life.userQuotes.joint.filter(q => q.id === id)[0][propName] = val;
    return this;
  }
}
