import _ from 'lodash';
import { STATES_ENUM } from './const';

const states = {
  [STATES_ENUM.DEFAULT]: {
    household_id: '',
    household_id_vers: '',
    aura_session_id: '',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.DEV_INIT]: {
    household_id: '8a1aeadd-d177-4100-bc05-213e51d8ed21',
    household_id_vers: 0,
    aura_session_id: 'b608c217-60c4-410c-9a91-54b2817a20ed',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOINT]: {
    household_id: 'a09640a7-af49-437b-900e-41787e601e42',
    household_id_vers: 0,
    aura_session_id: '0c9345e8-7556-49b7-9bb8-17cd86d2a4d3',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_1_INDIV]: {
    household_id: 'a09640a7-af49-437b-900e-41787e601e42',
    household_id_vers: 0,
    aura_session_id: '0c9345e8-7556-49b7-9bb8-17cd86d2a4d3',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_1_JOINT]: {
    household_id: '78a899b6-e2e7-436c-8af7-64ccd1e0a637',
    household_id_vers: 0,
    aura_session_id: '',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_1_INDIV_APPROVED]: {
    household_id: '14e2b5f1-ae27-40db-942f-58ce2470d38e',
    household_id_vers: 0,
    aura_session_id: '3e09a383-3f7b-4656-a463-8927194da984',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_1_JOINT_APPROVED]: {
    household_id: '78a899b6-e2e7-436c-8af7-64ccd1e0a637',
    household_id_vers: 0,
    aura_session_id: '3bff0add-4c4f-4672-bd3a-d920be539cf5',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_1_POLICYME_PARTNER]: {
    household_id: '2d3e3f3b-69cd-4740-8b84-089bb3661a9c',
    household_id_vers: 0,
    aura_session_id: 'e973a229-7531-4c4e-9714-b77660d561c6',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_1_JOINT_POLICYME_PARTNER]: {
    household_id: '628b068f-1a47-4512-855e-b2405b53374d',
    household_id_vers: 0,
    aura_session_id: '5da2ba14-b1f7-4240-a8ac-037e97b30677',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_3_INDIV_APPROVED]: {
    household_id: '591f5bb8-9bbf-412b-ba7b-6af5e9772e4f',
    household_id_vers: 0,
    aura_session_id: 'e35fabbf-4893-4446-892e-4fa751db720a',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_INDIVIDUAL_HD_GI]: {
    household_id: 'a09640a7-af49-437b-900e-41787e601e42',
    household_id_vers: 0,
    hd_session_id: 'df1e28b9-cb56-ca8a-8d1f-4d6b0a3c512a',
    hd_application_id: 'c01197bd-f1c9-4616-a3c0-2e87ed9650e3',
    hd_policy_id: 'cf1e28b9-ab56-4a8a-8d1f-4d6b0a3c512a',
    aura_session_id: '0c9345e8-7556-49b7-9bb8-17cd86d2a4d3',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
  [STATES_ENUM.JOURNEY_JOINT_CAA_MEMBERSHIP]: {
    household_id: "98d69bf3-010e-4f9c-88a6-7a509e763ad2",
    household_id_vers: 0,
    hd_session_id: "",
    hd_application_id: "",
    hd_policy_id: "",
    hd_family_id: "",
    aura_session_id: "e596729f-607b-44f5-a9f5-f137af61043f",
    promo_code: "",
    auth_num_attempts_remaining: "",
    auth_num_otp_attempts_remaining: "",
    auth_otp_authorized: "",
    auth_medium: "",
    auth_validate_email_phone: "",
    auth_verify_access_code: "",
    helcim_customer_code: "",
    twilio_token: "dummytoken",
    user_id: 37611,
  },
  [STATES_ENUM.JOURNEY_1_INDIV_QUEBEC]: {
    household_id: 'a09640a7-af49-437b-900e-41787e601e42',
    household_id_vers: 0,
    aura_session_id: '0c9345e8-7556-49b7-9bb8-17cd86d2a4d3',
    promo_code: '',
    auth_num_attempts_remaining: '',
    auth_num_otp_attempts_remaining: '',
    auth_otp_authorized: '',
    auth_medium: '',
    auth_validate_email_phone: '',
    auth_verify_access_code: '',
    helcim_customer_code: '',
  },
};

export class Session {
  constructor(strategy) {
    const stateObj = states[strategy] ? states[strategy] : states[STATES_ENUM.DEFAULT];
    const initialStateDeepCopy = _.cloneDeep(stateObj);
    Object.assign(this, initialStateDeepCopy);
  }
}
